apiVersion: v1
kind: Service
metadata:
  name: minusone-demo
  namespace: staging
spec:
  type: NodePort
  selector:
    app: minusone-demo
    environment: staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30100
