apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minusone-demo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:santi1s/kube-poc.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
