apiVersion: v1
kind: Service
metadata:
  name: minusone-demo
  namespace: production
spec:
  type: NodePort
  selector:
    app: minusone-demo
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30200
